<?php
define('USERS_TB', 'tasks_users');
define('TASKS_TB', 'tasks_user_tasks');
define('WORKERS_TB', 'tasks_workers');
define('PRIORITY_TB', 'tasks_priority_values');
define('WORK_TB', 'tasks_user_work');
define('WORK_FILES_TB', 'tasks_work_files');
define('PERIODICITY_TB', 'tasks_periodicity');
define('WORK_REPORTS_TB', 'tasks_user_works_reports');
define('TASKS_REPORTS_TB', 'tasks_users_tasks_reports');
define('MSGS_TB', 'tasks_messages');
define('CLIENT_MSGS_TB', 'tasks_clients_messages');
define('COMMENTS_TB', 'tasks_users_comments');
define('FOLDERS_TB', 'tasks_users_folders');
define('FILES_TB', 'tasks_users_files');
define('FILES_ACCESS_TB', 'tasks_users_files_access');
define('CLIENTS_FILES_TB', 'tasks_clients_files');
define('CLIENTS_FOLDERS_TB', 'tasks_clients_folders');
define('USER_IMAGES_TB', 'tasks_user_images');
define('USER_IMAGES_COORDS_TB', 'tasks_users_images_coordinats');
define('CONTACTS_TB', 'tasks_users_contacts');
define('USERS_POSITIONS_TB', 'tasks_users_positions');
define('DIFFICULTY_TB', ' tasks_tasks_difficulty');
define('ACTIVE_LOG_TB', ' tasks_active_log');
define('CLIENTS_TB', ' tasks_clients');
define('CLIENT_USER_ACCESS_TB', ' tasks_clients_users_access');
define('CLIENTS_ACCESSES_TB', 'tasks_clients_accesses');
define('DEALS_TB', ' tasks_deals');
define('DEALS_REMINDERS_TB', ' tasks_deals_reminders');
define('DEALS_STATUSES_DATA_TB', ' tasks_deals_statuses_data');
define('DEALS_TYPES_TB', ' tasks_deals_types');
define('DEALS_ACCESSES_TB', ' tasks_deals_users_access');
define('DEALS_STATUSES_TB', ' tasks_deals_statuses');
define('CLIENTS_TYPES_DATA', 'tasks_clients_organizations_types');
define('GOODS_TB', 'tasks_goods');
define('GOODS_REPORTS_TB', 'tasks_goods_reports');
define('GOODS_IMAGES_TB', 'tasks_goods_images');
define('GOODS_OWNERS_TB', 'tasks_goods_owners');
define('MONEY_TB', 'tasks_users_money');
define('MONEY_TYPES_TB', 'tasks_users_money_types');
define('MONEY_REPORTS_TB', 'tasks_users_money_reports');
define('COMPS_TB', 'tasks_users_computers');
define('WORK_ACTIVITY_TB', 'tasks_users_activity');
define('WORK_ACTIVITY_WORK_STARTED_TB', 'tasks_users_activity_work_started');
define('FILE_STATUS_DATA_TB', 'tasks_files_statuses_data');
define('FILE_STATUSES_TB', 'tasks_files_statuses');
define('CAMERAS_TB', 'tasks_users_cameras');
define('AUTO_TB', 'tasks_users_auto');
define('COLLEAGUES_TB', 'tasks_users_colleagues');
define('FINANCES_TB', 'tasks_users_finances');
define('CURRENCY_DATA_TB', 'tasks_currency_data');
define('FINANCE_OPERATIONS_TYPES_TB', 'tasks_finances_operations_types_data');
define('FINANCES_OPERATIONS_TB', 'tasks_finances_operations');
define('FINANCES_OPERATIONS_STATUSES_TYPES_TB', 'tasks_finances_operations_statuses_types');
define('FINANCES_OPERATIONS_STATUSES_TB', 'tasks_finances_operations_statuses');
define('FINANCES_ACCESS', 'tasks_users_finances_access');
define('USERS_STATUSES_TB', 'tasks_users_statuses');
define('USERS_STATUSES_DATA_TB', 'tasks_users_statuses_data');
define('PLANNING_TYPES_TB', 'tasks_users_planning_types');
define('PLANNING_TB', 'tasks_users_planning');
define('PLANNING_DATES_TB', 'tasks_users_planning_dates');
define('SMS_LOG_TB', 'tasks_sms_log');
define('MSGS_GROUPS_TB', 'tasks_messages_groups');
define('MSGS_GROUPS_MSGS_TB', 'tasks_messages_groups_messages');
define('MSGS_GROUPS_USERS_TB', 'tasks_messages_groups_users');
define('OFDOSC_TYPES_TB', 'tasks_users_ofdosc_types');
define('OFDOSC_TB', 'tasks_users_ofdosc');
define('OFDOCS_ACCESS_TB', 'tasks_users_ofdocs_access');
define('OFDOCS_STATUS_DATA_TB', 'tasks_ofdocs_statuses_data');
define('OFDOCS_STATUSES_TB', 'tasks_ofdocs_statuses');
define('REPRIMANDS_TB', 'tasks_reprimands');
define('DEPUTY_TB', 'tasks_deputies');
define('EXTERNAL_SERVICES_TB', 'tasks_external_services');
define('EXTERNAL_TB', 'tasks_external_users_services');
define('NOTES_TB', 'tasks_notes');
define('NOTE_VERISONS_TB', 'tasks_notes_versions');
define('NOTE_ACCESS_TB', 'tasks_notes_access');
define('REMOVE_FROM_WORK_TB', 'tasks_users_remove_from_work');
define('MONEY_ACCRUALS_TYPES_TB', 'tasks_money_accruals_types');
define('MONEY_ACCRUALS_TB', 'tasks_money_accruals');
define('ACCRUALS_IN_PAYMENTS_TB', 'tasks_money_accruals_in_payments');
define('PROJECTS_TB', 'tasks_projects');
define('PROJECTS_TASKS_REPORTS_TB', 'tasks_projects_tasks_reports');
define('PROJECT_TASKS_TB', 'tasks_projects_tasks');
define('PROJECT_REPORTS_TB', 'tasks_projects_reports');
define('DEALS_GROUPS_TB', 'tasks_deals_groups');
define('CNEWS_TB', 'tasks_cnews');
define('VIDEO_INS_TB', 'tasks_video_instructions');
define('VIDEO_INS_VIEWS_TB', 'tasks_video_instructions_views');
define('EVCAL_TB', 'tasks_calendar_of_events');
define('POSTTR_TB', 'tasks_post_trackings');
define('POSTTR_STATUSES_TB', 'tasks_post_trackings_statuses');
define('TASKS_DEALS_LINKS_TB', 'tasks_tasks_links_deals');
define('TASKS_SMS', 'tasks_tasks_sms');
define('TASKS_SMS_SENT', 'tasks_tasks_sms_sent');
?>
